### ISSUE TITLE
大佬，借个楼，我想问个您之前问的问题解决了吗？

### ISSUE THREAD

**Issue by Deprecated-Repositories** [Smoovsky/Aim-For-Offer-Solution-C-Sharp-Ver.#1]
我看您在这里问了个问题，
https://github.com/XTLS/Xray-core/issues/767
现在我和您的症状一模一样，我想请问下您的解决了吗？是否可以伸出援助之手帮我一下。。。

**Comment by Smoovsky** [comment]
> 我看您在这里问了个问题， [XTLS/Xray-core#767](https://github.com/XTLS/Xray-core/issues/767) 现在我和您的症状一模一样，我想请问下您的解决了吗？是否可以伸出援助之手帮我一下。。。

没有解决。觉得openwrt系的固件太束手束脚了，后面自己刷了个ubuntu用了。
